import { Component } from '../../ecs/component';

/**
 * Component that defines which faction an entity belongs to.
 * Used for AI decision making, relationship handling, and targeting.
 */
export class FactionComponent extends Component {
  public readonly name: string = 'FactionComponent';

  /**
   * Creates a new FactionComponent.
   * 
   * @param {string} factionId - The unique identifier of the faction (e.g., 'player', 'enemy_1').
   */
  constructor(public factionId: string) {
    super();
  }
}

/**
 * Component that marks an entity as a resource node.
 * Contains information about the resource type, amount, and regeneration.
 */
export class ResourceNodeComponent extends Component {
  public readonly name: string = 'ResourceNodeComponent';

  /**
   * Creates a new ResourceNodeComponent.
   * 
   * @param {string} resourceType - The type of resource (e.g., 'gold', 'wood').
   * @param {number} amount - The current amount of resource available.
   * @param {number} [maxAmount=amount] - The maximum amount of resource this node can hold.
   * @param {number} [regenRate=0] - The amount of resource regenerated per second.
   */
  constructor(
    public resourceType: string,
    public amount: number,
    public maxAmount: number = amount,
    public regenRate: number = 0
  ) {
    super();
  }
}

/**
 * Component that assigns a strategic value to a location or entity.
 * Used by the AI to determine important areas to capture or defend.
 */
export class StrategicValueComponent extends Component {
  public readonly name: string = 'StrategicValueComponent';

  /**
   * Creates a new StrategicValueComponent.
   * 
   * @param {number} value - The numeric strategic value (higher means more important).
   * @param {string} type - The type of strategic point (e.g., 'choke_point', 'high_ground', 'base').
   */
  constructor(public value: number, public type: string) {
    super();
  }
}

/**
 * Component that represents the threat level generated by an entity.
 * Used by the AI to prioritize targets and assess danger.
 */
export class ThreatComponent extends Component {
  public readonly name: string = 'ThreatComponent';

  /**
   * Creates a new ThreatComponent.
   * 
   * @param {number} baseThreat - The base threat level of the entity.
   * @param {number} [currentThreat=baseThreat] - The current threat level (can be modified by buffs/debuffs).
   */
  constructor(public baseThreat: number, public currentThreat: number = baseThreat) {
    super();
  }
}
